### ISSUE TITLE
Does not work with line-numbers

### ISSUE THREAD

**Issue by shadyalfred** [dandavison/magit-delta#18]
![image](https://user-images.githubusercontent.com/3685582/102580764-db9ce080-4107-11eb-85ec-0af4fc8f8a7d.png)

I'm not sure what this is, probably old commits' diffs or something. It shows up as soon as I open magit, and it's not even foldable nor collapsible.

**Comment by dandavison** [comment]
Hi @ShadyAlfred, the problem here is that `line-numbers` cannot be used<sup>1</sup> with `magit-delta`. So the question is, how does one activate `line-numbers` for normal Delta usage (including `git add -p`) but disable it for `magit-delta`? The best solution for that currently is to add `"--no-gitconfig"` to `magit-delta-delta-args`, for example like this:

```emacs-lisp
(add-to-list 'magit-delta-delta-args "--no-gitconfig")
```

Of course, the disadvantage there is that magit-delta won't use any of the colours configured in your gitconfig. There might be other ways of doing this in the future: it's an active issue in Delta (https://github.com/dandavison/delta/issues/307).

<sup>1</sup> As you can imagine, it's essential for the output that magit receives from Delta to be in the standard git patch format, without any line numbers or decorations etc, because magit is expecting to receive output from git, and magit uses that output to form its own patches to send to `git apply`. So the only "unusual" thing that Delta is allowed to add to the patch are ANSI colour codes (which are converted to emacs colours and removed from the patch by the xterm-color elisp library).

**Comment by shadyalfred** [comment]
Thanks, that fixed it. I found it indeed in my `.gitconfig` file, I had copied it from the snippet that was provided in the git delta repo.
